import React, { useState, useContext } from 'react';
import axios from 'axios';
import GlobalContext from '../Context/GlobalContext';
import Usuarios from './Usuarios';

export default function BarraBusquedaUsu() {
  //const [textoBusqueda,setTextoBusqueda] = useState('')
  const [ListaCoincidencias, SetListaCoincidencias] = useState([]);
  const { setUsuarios, usuarios } = useContext(GlobalContext);

  function AgregarUsuario(obj) {
    console.log(obj);
    setUsuarios((prevState) => {
      return [
        ...prevState.filter((item) => item.id !== obj.TERCEID_USU),
        {
          id: obj.TERCEID_USU,
          nombre: obj.NOMCOMPL_USU,
          checked: true,
          num: usuarios.length,
        },
      ];
    });
    SetListaCoincidencias([]);
    document.querySelector('#txtBusqueda').value = '';
  }

  function buscarUsuarios(e) {
    let textoBusqueda = e.target.value;
    // console.log(textoBusqueda)
    // console.log(ListaCoincidencias)
    if (e.target.value !== '') {
      axios
        .post(
          'frmCalendarioV2.aspx/ObtenerLisUsuariosxFiltro',
          { prefixText: textoBusqueda },
          {
            headers: { 'Content-Type': 'application/json' },
          }
        )
        .then((res) => {
          if (res.status === 200) {
            if (res.data.d !== undefined) {
              SetListaCoincidencias(res.data.d);
              //console.log(res.data.d)
            }
          }
        })
        .catch((error) => {
          //console.log(idUsuario)
          SetListaCoincidencias([
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1018,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '890210581',
              NOMCOMPL_USU: 'Area Metropolitana de Bucaramanga',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 2047,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1075302797',
              NOMCOMPL_USU: 'Carlos Alberto Gomez Aroca',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 2203,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1081161118',
              NOMCOMPL_USU: 'Carlos Andres Perdomo Torres',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 7,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1003827748',
              NOMCOMPL_USU: 'Carolina Valencia Baena',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 59,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '804003778',
              NOMCOMPL_USU: 'Concejo Municipal de Bucaramanga',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 55,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '800194000',
              NOMCOMPL_USU: 'Contraloria Distrital de Cartagena de Indias',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1127,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1117541619',
              NOMCOMPL_USU: 'David Ricardo Salazar Rodríguez',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 77,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '828000191',
              NOMCOMPL_USU:
                'Empresa Municipal de Servicios Publicos de Cartagena del Chairá',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 96,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '890701300',
              NOMCOMPL_USU: 'Hospital San Carlos E.S.E De Saldaña',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1036,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '91473393',
              NOMCOMPL_USU: 'Juan Carlos Montero Delgado',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 20,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1075310847',
              NOMCOMPL_USU: 'Juan Carlos Sanchez Vieda',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1864,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1140889380',
              NOMCOMPL_USU: 'Katleen Vanesa Carvajal de la Hoz',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 3286,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1075312048',
              NOMCOMPL_USU: 'Martha Natalia Leiva Scarpetta',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 37,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '800095754',
              NOMCOMPL_USU: 'Municipio Cartagena del Chaira',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 10,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '97435439',
              NOMCOMPL_USU: 'Oscar Eduardo Cuellar Rodriguez',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1117,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '12199989',
              NOMCOMPL_USU: 'Oscar Julián Rojas Garcés',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 3343,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '1075251604',
              NOMCOMPL_USU: 'Oscar Mauricio Lopez Morales',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1866,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '3716135',
              NOMCOMPL_USU: 'Rafael Antonio Carvajal Bustos',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
            {
              __type: 'Datos.T_USU',
              USUID_USU: 0,
              LOGIN_USU: null,
              TEMA_USU: null,
              FECHAULTINGO_USU: null,
              CLAVE_USU: null,
              BLOQ_USU: null,
              FECHAEXPIRA_USU: null,
              CONTEOPASWFALL_USU: null,
              ESTADO_USU: null,
              PERMITEMODNOVE_USU: null,
              PRGTAPASSWORD_USU: null,
              RTAPASSW_USU: null,
              TERMNOM_USU: null,
              IP_USU: null,
              FECCREA_USU: null,
              USUCREA_USU: null,
              TERMINAACT_USU: null,
              TERCEID_USU: 1607,
              PERFILADMIN_USU: null,
              IDIOMA_USU: null,
              NUMIDENT_USU: '93386631',
              NOMCOMPL_USU: 'Ricardo Alberto Bejarano Barragan',
              NIVELSEG_USU: null,
              CAMBIARALINGRESAR_USU: null,
              FECMOD_USU: null,
              USUMOD_USU: null,
              NOMROL_USU: null,
              BPM_USU: null,
              PRESU_USU: null,
              VEH_USU: null,
              PREDIAL_USU: null,
              CONTROLBLOOD_USU: null,
              IMPORENTAS_USU: null,
              IYC_USU: null,
              ERP_USU: null,
              REGISTRO_USU: null,
              REGISTROVER_USU: null,
              FECULTCAMBIOPASS_USU: null,
              CANTDIASCAMBIOPASS_USU: null,
              USUDELEGID_USU: null,
              USUDELEGNOM_USU: null,
              USUDELEGIDMOD_USU: null,
              USUDELEGNOMMOD_USU: null,
              PREFERENINI_USU: null,
              DOCUPGINIID_USU: null,
              TOKEN_USU: null,
              ESUSUESPECIAL_USU: null,
              TOKEN2_USU: null,
              VALIDAFECHALOGIN_USU: false,
              FECHAINICIAL_USU: '/Date(-62135578800000)/',
              FECHAFINAL_USU: '/Date(-62135578800000)/',
              ADMINFECHA_USU: false,
              TAMANIODRIVE_USU: 0,
              TAMANIOALBUM_USU: 0,
              ESUSUACUED_USU: null,
              ESUSUASEO_USU: null,
              PORTALCONTRIB_USU: null,
              CONFIRMAMAIL_USU: null,
            },
          ]);
        });
    } else {
      SetListaCoincidencias([]);
    }
  }

  return (
    <React.Fragment>
      <input
        type='text'
        id='txtBusqueda'
        onChange={buscarUsuarios}
        placeholder='  &#xf0c0;  Buscar a gente'
        style={{ fontFamily: 'FontAwesome' }}
        className='pt-2 border-0 text-black-200 text-l pb-2 w-full border-b-2 border-gray-200 focus:outline-none focus:ring-0 focus:border-blue-500  '
      />
      <ul className='suggestions'>
        {ListaCoincidencias.map((row, i) => (
          <React.Fragment key={i}>
            <li className='' onClick={() => AgregarUsuario(row)}>
              {row.NOMCOMPL_USU}
            </li>
          </React.Fragment>
        ))}
      </ul>
      {/* <ListaUsuarios lis = {ListaCoincidencias} /> */}
    </React.Fragment>
  );
}
